def getAgentDict(agent):
    agentDict = {}
    if agent['DisplayBusiness'] is not None:
        B = 'DisplayBusiness'
        agentDict = {
            'Salutation': agent['Name']['Salutation'],
            'FirstName': agent['Name']['FirstName'],
            'SecondName': agent['Name']['SecondName'],
            'FamilyName': agent['Name']['FamilyName'],
            'PostNominal': agent['Name']['PostNominal'],
            'FullName': agent['Name']['FullName'],
            'GivenName': agent['Name']['GivenName'],
            'MARN': agent['MARN'],
            'IsNoFee': agent['IsNoFee'],
            'ContactId': agent['ContactId'],
            'CitizenshipCountries': agent['CitizenshipCountries'],
            'OtherNames': agent['OtherNames'],
            'Aliases': agent['Aliases'],
            'Email': "NOT CHECKED",
            'FullAddress': "NOT CHECKED",

            'Business Relationship': agent[B]['Relationship'],
            'Business Classification': agent[B]['BusinessClassification'],
            'Business Type': agent[B]['BusinessType'],
            'Entity Name': agent[B]['EntityName'],
            'Business Name': agent[B]['Name'],
            'ABN': agent[B]['ABN'],
            'Business Country': agent[B]['Address']['Country'],
            'Bus_AddressLine1': agent[B]['Address']['AddressLine1'],
            'Bus_AddressLine2': agent[B]['Address']['AddressLine2'],
            'Bus_AddressLine3': agent[B]['Address']['AddressLine3'],
            'Bus_State': agent[B]['Address']['State'],
            'Bus_OtherState': agent[B]['Address']['OtherState'],
            'Bus_Suburb': agent[B]['Address']['Suburb'],
            'Bus_OtherSuburb': agent[B]['Address']['OtherSuburb'],
            'Bus_PostCode': agent[B]['Address']['PostCode'],
            'Bus_OtherPostCode': agent[B]['Address']['OtherPostCode'],
            'Bus_Latitude': agent[B]['Address']['Latitude'],
            'Bus_Longitude': agent[B]['Address']['Longitude'],
            'Bus_FullAddress': agent[B]['Address']['FullAddress'],
            'Business_P_Country': agent[B]['PostalAddress']['Country'],
            'Bus_P_AddressLine1': agent[B]['PostalAddress']['AddressLine1'],
            'Bus_P_AddressLine2': agent[B]['PostalAddress']['AddressLine2'],
            'Bus_P_AddressLine3': agent[B]['PostalAddress']['AddressLine3'],
            'Bus_P_State': agent[B]['PostalAddress']['State'],
            'Bus_P_OtherState': agent[B]['PostalAddress']['OtherState'],
            'Bus_P_Suburb': agent[B]['PostalAddress']['Suburb'],
            'Bus_P_OtherSuburb': agent[B]['PostalAddress']['OtherSuburb'],
            'Bus_P_PostCode': agent[B]['PostalAddress']['PostCode'],
            'Bus_P_OtherPostCode': agent[B]['PostalAddress']['OtherPostCode'],
            'Bus_P_FullAddress': agent[B]['PostalAddress']['FullAddress'],
            'Bus_P_Latitude': agent[B]['PostalAddress']['Latitude'],
            'Bus_P_Longitude': agent[B]['PostalAddress']['Longitude'],
            'Bus_Ph_CountryCode': agent[B]['Contact']['Phone']['CountryCode'],
            'Bus_Ph_AreaCode': agent[B]['Contact']['Phone']['AreaCode'],
            'Bus_Ph_Number': agent[B]['Contact']['Phone']['Number'],
            'Bus_Ph_FullNumber': agent[B]['Contact']['Phone']['FullNumber'],
            'Bus_Ph2_CountryCode': agent[B]['Contact']['Phone2']['CountryCode'],
            'Bus_Ph2_AreaCode': agent[B]['Contact']['Phone2']['AreaCode'],
            'Bus_Ph2_Number': agent[B]['Contact']['Phone2']['Number'],
            'Bus_Ph2_FullNumber': agent[B]['Contact']['Phone2']['FullNumber'],
            'Bus_WebsiteUrl': agent[B]['WebsiteUrl']
        }
    elif agent['PrimaryBusiness'] is not None:
        B = 'PrimaryBusiness'
        agentDict = {
            'Salutation': agent['Name']['Salutation'],
            'FirstName': agent['Name']['FirstName'],
            'SecondName': agent['Name']['SecondName'],
            'FamilyName': agent['Name']['FamilyName'],
            'PostNominal': agent['Name']['PostNominal'],
            'FullName': agent['Name']['FullName'],
            'GivenName': agent['Name']['GivenName'],
            'MARN': agent['MARN'],
            'IsNoFee': agent['IsNoFee'],
            'ContactId': agent['ContactId'],
            'CitizenshipCountries': agent['CitizenshipCountries'],
            'OtherNames': agent['OtherNames'],
            'Aliases': agent['Aliases'],
            'Email': "NOT CHECKED",
            'FullAddress': "NOT CHECKED",

            'Business Relationship': agent[B]['Relationship'],
            'Business Classification': agent[B]['BusinessClassification'],
            'Business Type': agent[B]['BusinessType'],
            'Entity Name': agent[B]['EntityName'],
            'Business Name': agent[B]['Name'],
            'ABN': agent[B]['ABN'],
            'Business Country': agent[B]['Address']['Country'],
            'Bus_AddressLine1': agent[B]['Address']['AddressLine1'],
            'Bus_AddressLine2': agent[B]['Address']['AddressLine2'],
            'Bus_AddressLine3': agent[B]['Address']['AddressLine3'],
            'Bus_State': agent[B]['Address']['State'],
            'Bus_OtherState': agent[B]['Address']['OtherState'],
            'Bus_Suburb': agent[B]['Address']['Suburb'],
            'Bus_OtherSuburb': agent[B]['Address']['OtherSuburb'],
            'Bus_PostCode': agent[B]['Address']['PostCode'],
            'Bus_OtherPostCode': agent[B]['Address']['OtherPostCode'],
            'Bus_Latitude': agent[B]['Address']['Latitude'],
            'Bus_Longitude': agent[B]['Address']['Longitude'],
            'Bus_FullAddress': agent[B]['Address']['FullAddress'],
            'Business_P_Country': agent[B]['PostalAddress']['Country'],
            'Bus_P_AddressLine1': agent[B]['PostalAddress']['AddressLine1'],
            'Bus_P_AddressLine2': agent[B]['PostalAddress']['AddressLine2'],
            'Bus_P_AddressLine3': agent[B]['PostalAddress']['AddressLine3'],
            'Bus_P_State': agent[B]['PostalAddress']['State'],
            'Bus_P_OtherState': agent[B]['PostalAddress']['OtherState'],
            'Bus_P_Suburb': agent[B]['PostalAddress']['Suburb'],
            'Bus_P_OtherSuburb': agent[B]['PostalAddress']['OtherSuburb'],
            'Bus_P_PostCode': agent[B]['PostalAddress']['PostCode'],
            'Bus_P_OtherPostCode': agent[B]['PostalAddress']['OtherPostCode'],
            'Bus_P_FullAddress': agent[B]['PostalAddress']['FullAddress'],
            'Bus_P_Latitude': agent[B]['PostalAddress']['Latitude'],
            'Bus_P_Longitude': agent[B]['PostalAddress']['Longitude'],
            'Bus_Ph_CountryCode': agent[B]['Contact']['Phone']['CountryCode'],
            'Bus_Ph_AreaCode': agent[B]['Contact']['Phone']['AreaCode'],
            'Bus_Ph_Number': agent[B]['Contact']['Phone']['Number'],
            'Bus_Ph_FullNumber': agent[B]['Contact']['Phone']['FullNumber'],
            'Bus_Ph2_CountryCode': agent[B]['Contact']['Phone2']['CountryCode'],
            'Bus_Ph2_AreaCode': agent[B]['Contact']['Phone2']['AreaCode'],
            'Bus_Ph2_Number': agent[B]['Contact']['Phone2']['Number'],
            'Bus_Ph2_FullNumber': agent[B]['Contact']['Phone2']['FullNumber'],
            'Bus_WebsiteUrl': agent[B]['WebsiteUrl']
        }

    else:
        agentDict = {
            'Salutation': agent['Name']['Salutation'],
            'FirstName': agent['Name']['FirstName'],
            'SecondName': agent['Name']['SecondName'],
            'FamilyName': agent['Name']['FamilyName'],
            'PostNominal': agent['Name']['PostNominal'],
            'FullName': agent['Name']['FullName'],
            'GivenName': agent['Name']['GivenName'],
            'MARN': agent['MARN'],
            'IsNoFee': agent['IsNoFee'],
            'ContactId': agent['ContactId'],
            'CitizenshipCountries': agent['CitizenshipCountries'],
            'OtherNames': agent['OtherNames'],
            'Aliases': agent['Aliases'],
            'Email': "NOT CHECKED",
            'FullAddress': "NOT CHECKED",

            'Business Relationship': None,
            'Business Classification': None,
            'Business Type': None,
            'Entity Name': None,
            'Business Name': None,
            'ABN': None,
            'Business Country': None,
            'Bus_AddressLine1': None,
            'Bus_AddressLine2': None,
            'Bus_AddressLine3': None,
            'Bus_State': None,
            'Bus_OtherState': None,
            'Bus_Suburb': None,
            'Bus_OtherSuburb': None,
            'Bus_PostCode': None,
            'Bus_OtherPostCode': None,
            'Bus_Latitude': None,
            'Bus_Longitude': None,
            'Bus_FullAddress': None,
            'Business_P_Country': None,
            'Bus_P_AddressLine1': None,
            'Bus_P_AddressLine2': None,
            'Bus_P_AddressLine3': None,
            'Bus_P_State': None,
            'Bus_P_OtherState': None,
            'Bus_P_Suburb': None,
            'Bus_P_OtherSuburb': None,
            'Bus_P_PostCode': None,
            'Bus_P_OtherPostCode': None,
            'Bus_P_FullAddress': None,
            'Bus_P_Latitude': None,
            'Bus_P_Longitude': None,
            'Bus_Ph_CountryCode': None,
            'Bus_Ph_AreaCode': None,
            'Bus_Ph_Number': None,
            'Bus_Ph_FullNumber': None,
            'Bus_Ph2_CountryCode': None,
            'Bus_Ph2_AreaCode': None,
            'Bus_Ph2_Number': None,
            'Bus_Ph2_FullNumber': None,
            'Bus_WebsiteUrl': None
        }
    return agentDict