on:
  workflow_dispatch

jobs:
  zip-files:
    name: Create file zip
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Zip files
        run: |
          echo "REPO_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV
          cd ../
          zip -r "${{ env.REPO_NAME }}.zip" "./${{ env.REPO_NAME }}/"
          print "${{ env.REPO_NAME }}"