on:
  workflow_dispatch

jobs:
  zip-files:
    name: Create file zip
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get vars set up
        run: |
          echo "REPO_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV
      - name: echo
        run: |
          echo "repo name: ${{ env.REPO_NAME }}"
          echo "direct reference to stupid var: ${{ github.event.repository.name }}"